# генерируется Quickshell (Настройки → Персонализация); вручную не править
font=JetBrainsMono Nerd Font:size=11.5
font-bold=JetBrainsMono Nerd Font:style=Bold:size=11.5
font-italic=JetBrainsMono Nerd Font:style=Italic:size=11.5

[colors-dark]
background=101615
foreground=d8e4e2
cursor=101615 d8e4e2
selection-background=26312f
selection-foreground=d8e4e2

regular0=26312f
regular1=cd8484
regular2=96cd84
regular3=cdb484
regular4=84a2cd
regular5=c184cd
regular6=84cdc7
regular7=d8e4e2

bright0=6c7f7c
bright1=dd9d9d
bright2=addd9d
bright3=ddc79d
bright4=9db7dd
bright5=d29ddd
bright6=9dddd7
bright7=eaf1f0
